server:
  port: 8761  # Eureka Server default

spring:
  application:
    name: new-auction-eureka-server

eureka:
  client:
    register-with-eureka: false   # ?? ??? ???? ??
    fetch-registry: false         # ????? ??? ???? ??
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka Server ??

  server:
    enable-self-preservation: true        # ?? ?? ? self-preservation ?? ????
    eviction-interval-timer-in-ms: 3000   # ??? ?? ?? (3?)

logging:
  level:
    com.netflix.eureka: OFF  # Eureka ?? ???
    com.netflix.discovery: OFF
