spring:
  application:
    name: new-auction-eureka-server
  security:
    user:
      name: admin
      password: admin

server:
  port: 8761  # Eureka Server default

eureka:
  client:
    register-with-eureka: false   # Eureka ???? ??? ? ?? ?? ???? ? ?? (?? ??)
    fetch-registry: false         # Eureka ??? ?? Eureka ????? ??? ??? ??? ??? ???

    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka Server ??

  server:
    enable-self-preservation: true        # ?? ?? ? self-preservation ?? ????
    eviction-interval-timer-in-ms: 30000  # ???? ?? ?? (?? 60?)


logging:
  level:
    com.netflix.eureka: OFF  # Eureka ?? ???
    com.netflix.discovery: OFF
